import {
  ClerkProvider,
  SignedIn,
  SignedOut
} from '@clerk/nextjs'
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Header } from './_components/header';
import { cn } from '~/lib/utils';
import { Guest } from './_components/guest';

export const metadata: Metadata = {
  title: "Yarn Palette",
  description: "Generated by mathiasev",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={cn("min-h-screen bg-background font-sans antialiased")}>
          <TRPCReactProvider>
            <Header />
            <div>
              <SignedOut>
                <Guest />
              </SignedOut>
              <SignedIn>
                {children}
              </SignedIn>
            </div>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider >
  );
}
